### ISSUE TITLE
Duplicate quotes

### ISSUE THREAD

**Issue by jucie** [fortrabbit/quotes#5]
This quotes occur more than once each:
2 : If you can't deploy your services independently then they aren't microservices.
2 : People that hate cats will come back as mice in their next life.

Caught by https://play.golang.org/p/iZFHbVbQbM

**Comment by frank-laemmer** [comment]
Solved with https://github.com/fortrabbit/quotes/commit/ebfe7e2e5695e06e7f6d16644b6ffb0b0eedd4b3
