### ISSUE TITLE
New quote: "We will not ship shit."

### ISSUE THREAD

**Issue by tristanlins** [fortrabbit/quotes#6]
> We will not ship shit.
> by Robert C. Martin

source: https://www.artima.com/weblogs/viewpost.jsp?thread=7588

PS: what is the right way to contribute? :-)

**Comment by frank-laemmer** [comment]
Solved with https://github.com/fortrabbit/quotes/commit/fedd03ec5529051a31fa845adcd690ffd64fa87c
